### ISSUE TITLE
"Just play a music" instead of "Just play some music"

### ISSUE THREAD

**Issue by lunananananananana** [alireza6677/lyrics-finder-gnome-ext#11]
I really like your extension, but it kinda annoys me that you say "Just play a music!" instead of "Just play some music!"

**Comment by TheWeirdDev** [comment]
You can change it for yourself. Just edit the downloaded source code.

I will fix this in the next release, but it might take a long time.

**Comment by TheWeirdDev** [comment]
It did take a long time :)
it is finally fixed.
