### ISSUE TITLE
Support Gnome 3.38

### ISSUE THREAD

**Issue by mike-to-spec** [alireza6677/lyrics-finder-gnome-ext#12]
I'd love to see Lyrics Finder support Gnome 3.38 (_well, an ABI for Gnome extensions in general but I digress_).

**Comment by TheWeirdDev** [comment]
Hi,
I have ported the extension to 3.38 on my local machine a few weeks ago, but there is a bug that makes it almost unusable.
Seems like the 'Label' widget in the new gnome-shell cannot display text bigger than a certain height. I gave it a blue background just to make it more obvious:

![image](https://user-images.githubusercontent.com/6321734/97087515-a14b2180-1637-11eb-912f-139c7770731f.png)

Asking Gnome developers might help (if didn't, i have some other workarounds in mind) but I'm currently busy, so for now this extension remains unsupported in 3.38 until I get back to it.

**Comment by mike-to-spec** [comment]
Thanks for the quick update, hope you find a solution soon.

**Comment by TheWeirdDev** [comment]
Seems like this bug is fixed in Gnome 40 beta. I will release an update after gnome-shell 40 is officially released.

**Comment by TheWeirdDev** [comment]
Hi everyone, 
I have updated the extension and now it should work on gnome-shell 40. (3.38 won't be supported)
You can install it using this repository or wait until it gets approved on the gnome extensions website.
