### ISSUE TITLE
Meta is null

### ISSUE THREAD

**Issue by tarzq28** [alireza6677/lyrics-finder-gnome-ext#13]
Hai dear developer, could you help me to fix this issue?
![Screenshot from 2021-01-19 16-00-04](https://user-images.githubusercontent.com/5894834/105011755-e4b6ff80-5a6f-11eb-979d-31ef913c6218.png)

**Comment by TheWeirdDev** [comment]
Even if I fix this issue there are a lot more to come. See [this](https://github.com/TheWeirdDev/lyrics-finder-gnome-ext/issues/12#issuecomment-716028304).
Gnome 3.38 broke a lot of APIs and I don't have time to fix it.

**Comment by TheWeirdDev** [comment]
Hi, I have upgraded the extension and now it should work on gnome-shell 40. (3.38 won't be supported)
You can install it using this repository or wait until it gets approved on the gnome extensions website.
