### ISSUE TITLE
The ly

### ISSUE THREAD

**Issue by M3t4ll1k0** [alireza6677/lyrics-finder-gnome-ext#15]
The lyrics text cut and disappear in most songs when scrolling down the lyrics in a 4k display with 300% as scale factor (10 feet gui in a HTPC) in ubuntu 21.04
![gnome-shell-screenshot-DJC470](https://user-images.githubusercontent.com/88471429/129078051-ee1350b5-4043-43ac-96c3-de44f8488538.png)

**Comment by TheWeirdDev** [comment]
Did you read my last comment in the other issue?I said this is caused by a bug in Gnome 3.38. 
It has nothing to do with your screen size. It happened on my 1080p monitor too.

I suggest you wait for the Ubuntu 21.10 or switch to a better distro that is not shipped with outdated software.

**Comment by TheWeirdDev** [comment]
Seems like you disappear after opening issues and won't read any of my comments. I don't see any reason to continue repeating myself, but for the last time: IT WON'T WORK ON GNOME 3.38

**Comment by M3t4ll1k0** [comment]
Sorry im new to gut hub, and the email notification about your response blended in the social inbox  which i dont use, sorry for he delay.
Second i thing your extension rocks, i was not here to diss on you, in fact totally he opposite, i registered here in my best effort to help you make your extension greater, sorry for the lack of knowledge and crappy report, im not a developer and this was my first time.
And... Yes the last version deployed during pandemic of ubuntu (21.04) is not up to the standards of lts version  im  used to but i was and brand new harwdare and i wnating to experience the cutting edge version, im experimenting a log trying to make a low end pc do the gaming 4k experience of a mid high pc using a external android tb box with an nvidia propietary ia algorithm that makes 720 like actual 4k.... anyway... saying my gnome its just not up to to date if not completely true, you skipped from 3.36 or 87
to 3.39 40.... know i know that's due a bug in that version of genome, but since you maintain version for way more outdated verions is not provably not being up to date but be to much and with the wrong version, dut?
Anyway wont change my SO, and since i dont code cant help you fix it for my os so i will just wahith for canonical roling a LTS.

Ironically in really outdated version of gnome there are extension similar yo yours, (but not close enough) not to mention your in true glory so if i was using a more oudated version i will have no isues. Not trying to argue, as i said im here to try to add my graint of salt.
If you have any coments, or wanna get in touch with me my personal email is alejandro.metalliko@gmail.com. I fell bad you fell ignorered where was completly the oposite, in fack y rearch truou gmail maulally to fin this amil, as i said thank for bringing us freedom and good FOSS

**Comment by TheWeirdDev** [comment]
Hi, sorry i got mad.
I don't maintain this extension for older gnome versions. The versions that are available for older gnome versions are also very old themselves. I only fix bugs that exist on the latest version and all older versions will be ignored.

Regarding that bug on Gnome 3.38, I can't really do much. I don't know how to fix it and I highly doubt Gnome developer will fix it either. I stopped using my own extension for 6 months waiting for Gnome 40 to be released! So if there was a way to make it work, i would have done it.

**Comment by M3t4ll1k0** [comment]
I respect your version mantaining policy, its up tu you its your proyect,
bit u runing arch i asume? Last version is vay far not the most used one. I
encorage yo to still backpoet big even if not ading fetures to the freezed
versions

**Comment by M3t4ll1k0** [comment]
Ok, i undestand, buggy version are the worst, i literally countingo dow to
next ubuntu to get new gnome, not onlly your version of extension has
isues, and i has lots of orreoe i really dont like the hippo
