### ISSUE TITLE
Add more sources

### ISSUE THREAD

**Issue by edurenye** [alireza6677/lyrics-finder-gnome-ext#2]
I can't find most of my lyrics, would be nice to be able to add more sources.
I would like to add these sources for instance: https://www.viasona.cat

**Comment by TheWeirdDev** [comment]
That website doesn't seem to have a REST API.
I would like to add more sources but most of them are paid and i can't afford them.

**Comment by edurenye** [comment]
I wrote them asking if they have a REST API.

**Comment by johnwiesel** [comment]
Thanks for the extension, I highly appreciate it. Sadly, many of the songs I listened to cannot be found. There are a bunch of Lyrics APIs listed here: https://www.programmableweb.com/category/lyrics/apis?category=20278
For example, genius ("Genius is the world’s biggest collection of song lyrics") seems to be free to use? https://genius.com/developers
At least I cannot find any limits, pricing, etc. at all not even in their terms.

**Comment by TheWeirdDev** [comment]
> Thanks for the extension, I highly appreciate it. Sadly, many of the songs I listened to cannot be found. There are a bunch of Lyrics APIs listed here: https://www.programmableweb.com/category/lyrics/apis?category=20278
> For example, genius ("Genius is the world’s biggest collection of song lyrics") seems to be free to use? https://genius.com/developers
> At least I cannot find any limits, pricing, etc. at all not even in their terms.

Thanks.
Unfortunately Genius API doesn't return the lyrics, it just returns a link to the website. But i have plans to add a new API in the next version. It might take a little time because i need to study for my exams.

**Comment by TheWeirdDev** [comment]
Good news. The new version is coming with a new API and it should fix the issue entirely.
