### ISSUE TITLE
Setting to allow custom font color

### ISSUE THREAD

**Issue by forsureitsme** [alireza6677/lyrics-finder-gnome-ext#4]
In my current dark shell theme, the font can't be seen. Not sure if it's transparent or the same color as the background. Would be nice if I could just force the color there.

![captura de tela de 2018-11-12 17-33-35](https://user-images.githubusercontent.com/2235293/48370909-a3618300-e6a1-11e8-85e6-482edca2aff2.png)

**Comment by TheWeirdDev** [comment]
Thanks for the good suggestion. I added this option in the new version.

You can  either wait until it's reviewed by a gnome team member or you can just [install it using this repo](https://github.com/TheWeirdDev/lyrics-finder-gnome-ext/blob/master/README.MD#how-to-install).
